[package]
name = "threshold_secret_sharing"
version = "0.1.0"
authors = [
  "Morten Dahl",
  "Mathieu Poumeyrol <mathieu.poumeyrol@snips.ai>"
]
description = "A pure-Rust implementation of various threshold secret sharing schemes"
keywords = [
  "threshold secret sharing", "secret sharing",
  "Shamir secret sharing",
  "packed secret sharing",
  "secure computation", "multi-party computation", "MPC",
  "cryptography", "crypto"
]
homepage = "https://github.com/snipsco/rust-threshold-secret-sharing"
documentation = "https://github.com/snipsco/rust-threshold-secret-sharing"
license = "MIT/Apache-2.0"

[features]
paramgen = ["primal"]

[dependencies]
rand = "0.3.*"
primal = { version = "0.2", optional = true }
