[package]
name = "threshold_secret_sharing"
version = "0.1.0"
authors = ["Morten Dahl <morten.dahl@snips.ai>", "Mathieu Poumeyrol <mathieu.poumeyrol@snips.ai>"]

[dependencies]
rand = "*"

[dev_dependencies]
